### ISSUE TITLE
When will the code be released? 

### ISSUE THREAD

**Issue by 869277160** [CZ-TAO12/DisenIDP#1]
Hi there, I noticed that the paper with this code has been published on CIKM, I want to know when will the author release the code?

**Comment by 869277160** [comment]
Also, I found some writing errors in the paper. For example, long-term and short-term influence in Figure 1 seems to be wrong.

**Comment by CZ-TAO12** [comment]
Hi, I have released our codes for the proposed DisenIDP and encourage discussions regarding it. I apologize for the issues you have mentioned. In Figure 1, kindly exchange the text description pertaining to the long-term and short-term influence.

**Comment by 869277160** [comment]
Thanks, I will close this issue.
